# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "validates_as_vat_number"
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alessandro Dal Grande", "Marco Sanson"]
  s.date = "2011-10-05"
  s.description = "Now you can validate VAT using the European service called VIES, \n                       to ensure it exists. Only require this gem and call validate_as_vat_number \n                       on your VAT field, in an Active Record object."
  s.email = "lab@develon.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".autotest",
    ".document",
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/validates_as_vat_number.rb",
    "rails/init.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/validates_as_vat_number_spec.rb"
  ]
  s.homepage = "http://github.com/develon/validates_as_vat_number"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Permits VAT validation within ActiveRecord using EU VIES Web Service."
  s.test_files = [
    "spec/spec_helper.rb",
    "spec/validates_as_vat_number_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<activerecord>, ["~> 2.3.5"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 2.5.11"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6"])
      s.add_development_dependency(%q<savon>, [">= 0.7.5"])
    else
      s.add_dependency(%q<activerecord>, ["~> 2.3.5"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 2.5.11"])
      s.add_dependency(%q<rspec>, ["~> 2.6"])
      s.add_dependency(%q<savon>, [">= 0.7.5"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 2.3.5"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 2.5.11"])
    s.add_dependency(%q<rspec>, ["~> 2.6"])
    s.add_dependency(%q<savon>, [">= 0.7.5"])
  end
end

